# Generated by Django 5.1.4 on 2025-02-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_image', models.ImageField(upload_to='clients')),
                ('client_email', models.EmailField(max_length=254)),
                ('client_contact_number', models.PositiveBigIntegerField()),
                ('client_address', models.TextField(default='Please enter the address.')),
            ],
        ),
    ]
