# Generated by Django 5.1.4 on 2025-02-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_logo', models.ImageField(upload_to='projects')),
                ('project_description', models.TextField(default='Enter the project description.')),
                ('project_duration', models.CharField(max_length=100)),
            ],
        ),
    ]
